# Generated by Django 5.0.6 on 2024-06-17 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PassageModel',
        ),
    ]
