# Generated by Django 5.0.6 on 2024-06-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_delete_passagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('passage', models.TextField()),
            ],
        ),
    ]
